Feature/mvvm
Insteration/Magic8BallGame pull request #2
Opened 2019-10-02 13:49 UTC by Insteration

Check hm2

2019-10-02 14:49 UTC, yalantis-ios-school requested changes

2019-10-02 14:49 UTC, yalantis-ios-school commented on .gitignore
> +Pods/
где весь остальной контент .gitignore?) Стандартный .gitignore для свифт проектов подходит для использования как есть, без изменений

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewController/BallViewController.swift
> +        let viewModel = BallViewModel(model: APIModel())
Внутри контроллера не должны создаваться его зависимости. Тот, кто создает контроллер, для него создает модель и вью модель. Соответственно, в данном случае в AppDelegate надо создавать модель и вью модель, и затем засеттить вью модель в контроллер

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewController/BallViewController.swift
> +    @objc func action(sender: UIBarButtonItem) {
private

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewController/BallViewController.swift
> +    @objc func getDefaultStatusForAnswerBar() {
private

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewController/BallViewController.swift
> +    @objc func cgeckDeviceMotion() {
private

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewModel/BallViewModel.swift
> +    private let options = Options()
этого не должно быть в ViewModel - она ответственна только за форматирование данных, а не за принятие решения, какие данные отображать. Это должно быть в модели

2019-10-02 14:49 UTC, yalantis-ios-school commented on Magic8BallGame/ViewModel/BallViewModel.swift
> +        if Reachability.isConnectedToNetwork() {
Reachability тоже должен быть в модели, не в вью модели. Это логика

2019-10-02 14:49 UTC, yalantis-ios-school commented on Podfile
> +pod 'SwiftLint'
укажи минимальные версии SwiftLint и SwiftGen

2019-10-02 14:49 UTC, yalantis-ios-school commented on swiftgen.yml
> +strings:
я не увидел:
1. Активной модели из MVVM стека - где BallModel, в которой вся логика экрана с шариком? Она должна проверять, есть ли интернет, и если да, то говорить API сервису "загрузи данные", а если нет, то говорить другому сервису "хранилищу данных" "дай ответы" и выбрать рандомный. И потом этот результат будет отображен на экране через вью модель.
2. Четко выделенный сервис, работающий с хранилищем данных. Options чем-то на него похож, и так как в этом проекте нет возможности добавлять свои ответы, его достаточно переименовать в AnswersStorage и сделать один метод "answers", который будет возвращать массив сущностей слоя Application. При этом, внутри себя он должен хранить ответы не в виде массива строк, а в виде Data сущностей, например, StorableAnswer. Как было в лекции, опять же 
3. Протоколов на API и сервис хранения данных
4. Три слоя данных - как было в лекции, отдельные типы данных Data (только для хранилища), Application (для модели и других сервисов - API например) и Presentation (для контроллера). Здесь везде стринги, нужны три модели, пускай они и будут одинаковыми
5. Не увидел uppercased форматирования ответа - это должно происходить в ViewModel и соответственно в Presentable сущности
6. MVVM стек для второго экрана - BallOptionsViewController

2019-10-03 09:02 UTC, yalantis-ios-school requested changes
Внесите правки по комментариям и самостоятельно закройте МР

2019-10-03 09:02 UTC, yalantis-ios-school commented on Magic8BallGame/MainFlow/Application/Model/BallModel.swift
> +    init(api: APIModel, answersStorage: DataAnswer) {
в параметрах и соответственно в свойствах должны использовать не фактические классы, а протоколы APIModelProtocol и DataAnswerProtocol соответственно, чтобы не было высокой связности

2019-10-03 09:02 UTC, yalantis-ios-school commented on Magic8BallGame/MainFlow/Application/ViewModel/BallViewModel.swift
> +            self.stateHandler!(answer.toPresentableAnswer())
тут опасно использовать !, лучше через ?

2019-10-03 09:02 UTC, yalantis-ios-school commented on Magic8BallGame/OptionsFlow/Application/ViewModel/BallOptionsViewModel.swift
> +    func getNumberOfHardAnswers(completion: @escaping (_ answers: [String]) -> Void) {
здесь тоже должны использоваться PresentableAnswer, не String. И нейминг неверный - возвращается не количество, а массив

2019-10-03 09:02 UTC, yalantis-ios-school commented on Magic8BallGame/OptionsFlow/Presentation/ViewController/BallOptionsViewController.swift
> +            for get in answers {
get?) answer понятнее

2019-10-03 09:02 UTC, yalantis-ios-school commented on Magic8BallGame/StorageFlow/Storage/DataAnswer.swift
> +    var text = ""
тут у меня возникла путаница, что это за стракт. Это пассивная модель или сервис хранения данных. Больше похоже на второе, но метод toAnswer() не вписывается никак.

2019-10-10 09:09 UTC, closed without merging

2019-10-10 09:09 UTC, Insteration commented
Fixed